### ISSUE TITLE
Management command to test email configuration

### ISSUE THREAD

**Issue by JeremyGibson** [caktus/jade-truffle#27]
The idea is to have a management command that will allow a dev to easily test email setup from a deployed system:

`staging@my-worker >$ ./manage.py send_test_email --from=no-reply --to=me@caktusgroup.com`

**Comment by kmtracey** [comment]
https://docs.djangoproject.com/en/3.2/ref/django-admin/#sendtestemail is in Django from 1.9 onwards...

**Comment by JeremyGibson** [comment]
lol


*Jeremy Gibson*Developer

***@***.*** ***@***.***>
www.caktusgroup.com
<http://www.google.com/url?q=http%3A%2F%2Fwww.caktusgroup.com%2F&sa=D&sntz=1&usg=AFQjCNG6RpHdHUA5QLae7099-vwv2NLrvg>
